### ISSUE TITLE
Some components are throwing "Minified React error #321" when used.

### ISSUE THREAD

**Issue by b3h3m0th** [AthenicAustria/athenic-ui#2]
This is probably an issue with the bundling (webpack). I have no idea why this is happening and what causes the issue.

**Comment by b3h3m0th** [comment]
Problem fixed! Thanks to @tmhao2005! ([Awesome answer on Stackoverflow](https://stackoverflow.com/questions/66634255/why-are-some-components-in-my-react-ts-component-library-throwing-minified-react))

**Comment by tmhao2005** [comment]
haha no worries :)
